
MODULE FIELD_3IM_FACTORY_MODULE


USE FIELD_3IM_MODULE
USE FIELD_2IM_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

INTERFACE FIELD_NEW
  MODULE PROCEDURE FIELD_3IM_NEW_OWNER
  MODULE PROCEDURE FIELD_3IM_NEW_WRAPPER
  MODULE PROCEDURE FIELD_3IM_NEW_GANG_WRAPPER
  MODULE PROCEDURE FIELD_3IM_NEW_GANG_OWNER
END INTERFACE

INTERFACE

MODULE SUBROUTINE FIELD_3IM_NEW_GANG_WRAPPER (FIELD_PTR, CHILDREN, LBOUNDS, PERSISTENT, DATA, SYNC_ON_FINAL, INITIALIZED)


CLASS(FIELD_3IM), POINTER :: FIELD_PTR
TYPE(FIELD_2IM_PTR), ALLOCATABLE :: CHILDREN (:)
INTEGER(KIND=JPIM), TARGET, INTENT (IN) :: DATA (:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL
LOGICAL, OPTIONAL,  INTENT(IN) :: INITIALIZED

END SUBROUTINE

MODULE SUBROUTINE FIELD_3IM_NEW_GANG_OWNER (FIELD_PTR, CHILDREN, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE)


CLASS(FIELD_3IM), POINTER :: FIELD_PTR
TYPE(FIELD_2IM_PTR), ALLOCATABLE :: CHILDREN (:)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: INIT_VALUE

END SUBROUTINE


END INTERFACE

PUBLIC :: FIELD_NEW

CONTAINS

SUBROUTINE FIELD_3IM_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, &
&                                 POOLED)

USE FIELD_STATISTICS_MODULE

CLASS(FIELD_3IM), POINTER :: FIELD_PTR
TYPE(FIELD_3IM_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (3)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: INIT_VALUE
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED

END SUBROUTINE

SUBROUTINE FIELD_3IM_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)

USE FIELD_STATISTICS_MODULE

CLASS(FIELD_3IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), TARGET, INTENT (IN) :: DATA (:,:,:)
TYPE(FIELD_3IM_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (3)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL
LOGICAL, OPTIONAL,  INTENT(IN) :: INITIALIZED

END SUBROUTINE


END MODULE

