SUBROUTINE TOTO(YDVFE,YDCVER,CDOPER,CDBC,KPROMA,KST,KEND,KFLEV,PIN,POUT,POUTS,PINS,KCHUNK,KLOUT)

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8, JPRD = 8
INTEGER, PARAMETER :: NULERR = 0

TYPE TVFE
  REAL(KIND=JPRB),ALLOCATABLE :: VFE_KNOT(:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTE(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTBF00 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTBF11 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERI(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERB(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBF00 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBF01 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBF10 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBF11 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBH00 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBH01 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDDERI(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDDERBF01(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTGW(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERGW(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTG(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTC(:) 
END TYPE TVFE

TYPE TCVER
LOGICAL :: LAPRXPK
INTEGER(KIND=JPIM) :: NDLNPR
REAL(KIND=JPRB) :: RHYDR0
LOGICAL :: LREGETA
LOGICAL :: LVFE_REGETA
INTEGER(KIND=JPIM) :: NVFE_TYPE
INTEGER(KIND=JPIM) :: NVFE_ORDER
INTEGER(KIND=JPIM) :: NVFE_INTERNALS
LOGICAL :: LVERTFE
LOGICAL :: LVFE_LAPL_BC
LOGICAL :: LVFE_GW
LOGICAL :: LVFE_GW_HALF
LOGICAL :: LVFE_GWMPA
LOGICAL :: LVFE_CHEB
LOGICAL :: LVFE_ECMWF
LOGICAL :: LVFE_NOBC
LOGICAL :: LVFE_VERBOSE
LOGICAL :: LVFE_NORMALIZE
LOGICAL :: LDYN_ANALYSIS_STABILITY
LOGICAL :: LPERCENTILS
LOGICAL :: LVFE_COMPATIBLE
LOGICAL :: LVFE_FD_MIX
LOGICAL :: LVFE_SILAPL
LOGICAL :: LVFD_COMPATIBLE
LOGICAL :: LREFINE_NHPRE_BBC
REAL(KIND=JPRB) :: RVFE_ALPHA
REAL(KIND=JPRB) :: RVFE_BETA
REAL(KIND=JPRB) :: RVFE_KNOT_STRETCH
REAL(KIND=JPRB) :: RFAC1, RFAC2
CHARACTER(LEN=8) :: CVFE_ETAH
END TYPE TCVER


TYPE(TVFE),TARGET ,INTENT(IN) :: YDVFE
TYPE(TCVER)       ,INTENT(IN) :: YDCVER
CHARACTER(LEN=*)  ,INTENT(IN) :: CDOPER
CHARACTER(LEN=2)  ,INTENT(IN) :: CDBC
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA, KST, KEND, KFLEV
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KCHUNK,KLOUT
REAL(KIND=JPRB)   ,INTENT(IN) :: PIN(KPROMA,0:KFLEV+1)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT):: POUT(KPROMA,*),POUTS(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PINS(KPROMA)

LOGICAL :: LLVERINT_ON_CPU

CHARACTER(LEN=2)   :: CLBC
INTEGER(KIND=JPIM) :: ILEVIN, ILEVOUT, IND, IEND, ITYPE, JCHUNK
REAL(KIND=JPRD),CONTIGUOUS,POINTER :: ZOPER(:,:)
REAL(KIND=JPRD) :: ZOUTS(KPROMA)
INTEGER(KIND=JPIM) :: IMAXTHREADS

!WHEN REMOVING THIS CONDITION THE ASM FILE WILL CONTAINS INSTRUCTION
!BUT IT WON'T IF THE FOLLOWING CONDITION IS PRESENT.
!CHECK toto.s TO SEE THE PROBLEM
IF (LLVERINT_ON_CPU) THEN
! IMAXTHREADS = OML_MAX_THREADS ()
ELSE
  IMAXTHREADS = 1 
ENDIF

!*   1. Initialization and control
!    -----------------------------

IF (YDCVER%LVFE_ECMWF) THEN
  IF (CDOPER(1:4) /= 'FDER'.OR.YDCVER%LVFE_NOBC) THEN
    CLBC='XX' ! no BC applied for derivatives
  ELSE
    CLBC='BC' ! BC according to Hortal applied on derivatives
  ENDIF
ELSE
  CLBC=CDBC
ENDIF


!*   2. Set operator size according to boundary conditions applied
!    --------------------------------------------------------------

IF (CDOPER(1:4)=='FDER'.OR.CDOPER(1:4)=='DDER') THEN
  ILEVOUT = KFLEV
ELSE
  ILEVOUT = KFLEV+1
ENDIF

IF (CDOPER(1:4)=='IBOT') THEN
  ITYPE=1
ELSE
  ITYPE=0
ENDIF

IF (CDOPER(1:4)=='INGW'.OR.CDOPER(1:4)=='DEGW') THEN
  IND=0
  ILEVIN = KFLEV+1
ELSEIF (CLBC=='XX'.OR.CDOPER=='INTG') THEN
  IND=1
  ILEVIN = KFLEV
ELSE
  IND=0
  ILEVIN = KFLEV+2
ENDIF
IEND=ILEVIN-1+IND

!*   3. Set operator according to boundary conditions applied
!    --------------------------------------------------------

!*   3.1 Vertical integral
!    ---------------------
IF (CDOPER(1:4)=='INGW') THEN
  write(0,*) "oper INWG",present(KLOUT),present(PINS)
  ZOPER => YDVFE%RINTGW(:,:)
ELSEIF (ANY(CDOPER(1:4) == (/'ITOP','IBOT'/))) THEN
  IF (CLBC=='XX') THEN
    ZOPER => YDVFE%RINTE(:,:)
  ELSEIF (CLBC=='00') THEN
    ZOPER => YDVFE%RINTBF00(:,:)
  ELSEIF (CLBC=='11') THEN
    ZOPER => YDVFE%RINTBF11(:,:)
  ELSE
    WRITE(NULERR,*) 'VERDISINT: ITOP/IBOT NOT IMPLEMENTED FOR CDBC=',CLBC
!   CALL ABOR1(' VERDISINT: ABOR1 CALLED')
  ENDIF
ELSEIF (CDOPER=='INTG') THEN
  ZOPER => YDVFE%RINTG(:,:)
ENDIF

!*   3.2 Vertical derivative
!    -----------------------

IF (CDOPER(1:4)=='DEGW') THEN
  ZOPER => YDVFE%RDERGW(:,:)
ELSEIF (CDOPER(1:4)=='HDER') THEN
  IF (CLBC=='00') THEN
    ZOPER => YDVFE%RDERBH00(:,:)
  ELSEIF (CLBC=='01') THEN
    ZOPER => YDVFE%RDERBH01(:,:)
  ELSE
    WRITE(NULERR,*) 'VERDISINT: HDER NOT IMPLEMENTED FOR CDBC=',CLBC
!   CALL ABOR1(' VERDISINT: ABOR1 CALLED')
  ENDIF
ELSEIF (CDOPER(1:4)=='FDER') THEN
  IF (CLBC=='XX') THEN
    ZOPER => YDVFE%RDERI(:,:)
  ELSEIF (CLBC=='BC') THEN
    ZOPER => YDVFE%RDERB(:,:)
  ELSEIF (CLBC=='00') THEN
    ZOPER => YDVFE%RDERBF00(:,:)
  ELSEIF (CLBC=='01') THEN
    ZOPER => YDVFE%RDERBF01(:,:)
  ELSEIF (CLBC=='10') THEN
    ZOPER => YDVFE%RDERBF10(:,:)
  ELSEIF (CLBC=='11') THEN
    ZOPER => YDVFE%RDERBF11(:,:)
  ELSE
    WRITE(NULERR,*) 'VERDISINT: FDER NOT IMPLEMENTED FOR CDBC=',CLBC
!   CALL ABOR1(' VERDISINT: ABOR1 CALLED')
  ENDIF
ELSEIF (CDOPER(1:4)=='DDER') THEN
  IF (CLBC=='XX') THEN
    ZOPER => YDVFE%RDDERI(:,:)
  ELSEIF (CLBC=='01') THEN
    ZOPER => YDVFE%RDDERBF01(:,:)
  ELSE
    WRITE(NULERR,*) 'VERDISINT: DDER NOT IMPLEMENTED FOR CDBC=',CLBC
!   CALL ABOR1(' VERDISINT: ABOR1 CALLED')
  ENDIF
ENDIF

CALL TITI (ZOPER)

END SUBROUTINE TOTO
