MODULE MODE_SEAICE_SICE

IMPLICIT NONE
PUBLIC

TYPE :: MODEL_FIELD
  CHARACTER( LEN = 64 ) :: CNAME      = '' 
  CHARACTER( LEN = 64 ) :: CCOMMENT   = '' 
  CHARACTER( LEN = 16 ) :: CUNITS     = '' 

  INTEGER               :: NCONFIG(2) = [0,0]   
  LOGICAL               :: LDIAG      = .FALSE. 
  LOGICAL               :: LINTERNAL  = .FALSE. 
  LOGICAL               :: LDEPENDENT = .FALSE. 

  REAL, POINTER         :: P1(:)      => NULL() 
  REAL, POINTER         :: P2(:,:)    => NULL() 
  REAL                  :: XDEFAULT   =  0.
END TYPE MODEL_FIELD

CONTAINS

SUBROUTINE UNPACK( MF, MASK )
IMPLICIT NONE
  TYPE(MODEL_FIELD), INTENT(INOUT) :: MF(:) 
  INTEGER, INTENT(IN) :: MASK(:) 

  LOGICAL, ALLOCATABLE :: G_CLEANUP_MASK(:)
  INTEGER :: N_CLEANUP_SIZE

  INTEGER :: I,J,K

  DO I = 1, SIZE( MF )
    WHERE([( .NOT.ANY( MASK == J ), J = 1, SIZE( MF(I)%P1 ) )]) MF(I)%P1 = MF(I)%XDEFAULT
  END DO

  IF(ALLOCATED(G_CLEANUP_MASK)) DEALLOCATE(G_CLEANUP_MASK)

END SUBROUTINE UNPACK

END MODULE MODE_SEAICE_SICE
