
MODULE FIELD_5LM_GATHER_MODULE


USE FIELD_5LM_MODULE
USE FIELD_5LM_ACCESS_MODULE
USE FIELD_5LM_FACTORY_MODULE
USE FIELD_SHUFFLE_TYPE_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_5LM_SHUFFLE_MODULE


IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_SHUFFLE


PUBLIC :: FIELD_5LM_GATHER_DEVICE_DATA_RDONLY

PUBLIC :: SFIELD_5LM_GATHER_DEVICE_DATA_RDONLY


PUBLIC :: FIELD_5LM_GATHER_DEVICE_DATA_RDWR

PUBLIC :: SFIELD_5LM_GATHER_DEVICE_DATA_RDWR


PUBLIC :: FIELD_5LM_GATHER_HOST_DATA_RDONLY

PUBLIC :: SFIELD_5LM_GATHER_HOST_DATA_RDONLY


PUBLIC :: FIELD_5LM_GATHER_HOST_DATA_RDWR

PUBLIC :: SFIELD_5LM_GATHER_HOST_DATA_RDWR


CONTAINS

FUNCTION FIELD_5LM_GATHER_DEVICE_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5LM),   POINTER, INTENT (IN) :: YLF

LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5LM_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_5LM_GATHER_DEVICE_DATA_RDONLY

SUBROUTINE SFIELD_5LM_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
LOGICAL(KIND=JPLM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5LM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDONLY (SELF%FIELD_5LM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5LM_GATHER_DEVICE_DATA_RDONLY

FUNCTION FIELD_5LM_GATHER_DEVICE_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5LM),   POINTER, INTENT (IN) :: YLF

LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5LM_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_5LM_GATHER_DEVICE_DATA_RDWR

SUBROUTINE SFIELD_5LM_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
LOGICAL(KIND=JPLM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5LM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDWR (SELF%FIELD_5LM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5LM_GATHER_DEVICE_DATA_RDWR

FUNCTION FIELD_5LM_GATHER_HOST_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5LM),   POINTER, INTENT (IN) :: YLF

LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5LM_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_5LM_GATHER_HOST_DATA_RDONLY

SUBROUTINE SFIELD_5LM_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
LOGICAL(KIND=JPLM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5LM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDONLY (SELF%FIELD_5LM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5LM_GATHER_HOST_DATA_RDONLY

FUNCTION FIELD_5LM_GATHER_HOST_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5LM),   POINTER, INTENT (IN) :: YLF

LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5LM_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_5LM_GATHER_HOST_DATA_RDWR

SUBROUTINE SFIELD_5LM_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
LOGICAL(KIND=JPLM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5LM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDWR (SELF%FIELD_5LM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5LM_GATHER_HOST_DATA_RDWR


END MODULE FIELD_5LM_GATHER_MODULE
