
MODULE FIELD_SHUFFLE_TYPE_MODULE


USE FIELD_3IM_MODULE, ONLY : FIELD_3IM
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_2RM_SHUFFLE_MODULE
USE FIELD_3RM_SHUFFLE_MODULE
USE FIELD_4RM_SHUFFLE_MODULE
USE FIELD_5RM_SHUFFLE_MODULE
USE FIELD_2RD_SHUFFLE_MODULE
USE FIELD_3RD_SHUFFLE_MODULE
USE FIELD_4RD_SHUFFLE_MODULE
USE FIELD_5RD_SHUFFLE_MODULE
USE FIELD_2IM_SHUFFLE_MODULE
USE FIELD_3IM_SHUFFLE_MODULE
USE FIELD_4IM_SHUFFLE_MODULE
USE FIELD_5IM_SHUFFLE_MODULE
USE FIELD_2LM_SHUFFLE_MODULE
USE FIELD_3LM_SHUFFLE_MODULE
USE FIELD_4LM_SHUFFLE_MODULE
USE FIELD_5LM_SHUFFLE_MODULE

IMPLICIT NONE

PRIVATE

TYPE FIELD_SHUFFLE
  INTEGER (KIND=JPIM) :: KGPBLKS_G = -1, KLON_G = -1, KGPTOT_G = -1
  INTEGER (KIND=JPIM) :: KGPBLKS_S = -1, KLON_S = -1, KGPTOT_S = -1
  INTEGER (KIND=JPIM) :: KGPBLKS   = -1, KLON   = -1, KGPTOT   = -1 ! alias for KGPBLKS, KLON, KGPTOT
  INTEGER (KIND=JPIM) :: KBLKMIN, KBLKMAX
  LOGICAL :: LFULL = .FALSE.  ! No need to gather/scatter, all columns are OK, return pointers based on original fields
  LOGICAL :: LNULL = .FALSE.  ! No need to gather/scatter, all columns are KO, return pointers on empty arrays
  CLASS (FIELD_3IM), POINTER :: YLFINDS => NULL ()
  TYPE (FIELD_2RM_SHUFFLE_PAIR), POINTER :: FIELD_2RM_LIST => NULL ()
  TYPE (FIELD_3RM_SHUFFLE_PAIR), POINTER :: FIELD_3RM_LIST => NULL ()
  TYPE (FIELD_4RM_SHUFFLE_PAIR), POINTER :: FIELD_4RM_LIST => NULL ()
  TYPE (FIELD_5RM_SHUFFLE_PAIR), POINTER :: FIELD_5RM_LIST => NULL ()
  TYPE (FIELD_2RD_SHUFFLE_PAIR), POINTER :: FIELD_2RD_LIST => NULL ()
  TYPE (FIELD_3RD_SHUFFLE_PAIR), POINTER :: FIELD_3RD_LIST => NULL ()
  TYPE (FIELD_4RD_SHUFFLE_PAIR), POINTER :: FIELD_4RD_LIST => NULL ()
  TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER :: FIELD_5RD_LIST => NULL ()
  TYPE (FIELD_2IM_SHUFFLE_PAIR), POINTER :: FIELD_2IM_LIST => NULL ()
  TYPE (FIELD_3IM_SHUFFLE_PAIR), POINTER :: FIELD_3IM_LIST => NULL ()
  TYPE (FIELD_4IM_SHUFFLE_PAIR), POINTER :: FIELD_4IM_LIST => NULL ()
  TYPE (FIELD_5IM_SHUFFLE_PAIR), POINTER :: FIELD_5IM_LIST => NULL ()
  TYPE (FIELD_2LM_SHUFFLE_PAIR), POINTER :: FIELD_2LM_LIST => NULL ()
  TYPE (FIELD_3LM_SHUFFLE_PAIR), POINTER :: FIELD_3LM_LIST => NULL ()
  TYPE (FIELD_4LM_SHUFFLE_PAIR), POINTER :: FIELD_4LM_LIST => NULL ()
  TYPE (FIELD_5LM_SHUFFLE_PAIR), POINTER :: FIELD_5LM_LIST => NULL ()
CONTAINS
  GENERIC :: INIT => INIT_FIELD_SHUFFLE
  PROCEDURE :: INIT_FIELD_SHUFFLE
  PROCEDURE :: SCATTER => SCATTER_FIELD_SHUFFLE
END TYPE FIELD_SHUFFLE

PUBLIC :: FIELD_SHUFFLE

INTEGER (KIND=JPIM), PARAMETER :: NLONDIM = 1, NBLKDIM = 2

CONTAINS

SUBROUTINE INIT_FIELD_SHUFFLE (SELF, KGPTOT, KLON_S, KLON_G, KBLKOFF)

USE FIELD_ABORT_MODULE

CLASS (FIELD_SHUFFLE) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KGPTOT
INTEGER (KIND=JPIM), INTENT (IN) :: KLON_S, KLON_G
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KBLKOFF

INTEGER (KIND=JPIM), POINTER :: INDS (:,:,:)
INTEGER (KIND=JPIM) :: JLONS, JBLKS, JLONG, JBLKG, I1S, I2S
INTEGER (KIND=JPIM) :: IBLKOFF

IBLKOFF = 1
IF (PRESENT (KBLKOFF)) IBLKOFF = KBLKOFF

SELF%KGPTOT_S  = KGPTOT
SELF%KLON_S    = KLON_S
SELF%KGPBLKS_S = (SELF%KGPTOT_S+SELF%KLON_S-1) / SELF%KLON_S

SELF%KGPTOT_G  = KGPTOT
SELF%KLON_G    = KLON_G
SELF%KGPBLKS_G = (SELF%KGPTOT_G+SELF%KLON_G-1) / SELF%KLON_G

SELF%KGPTOT  =  SELF%KGPTOT_G 
SELF%KLON    =  SELF%KLON_G   
SELF%KGPBLKS =  SELF%KGPBLKS_G

SELF%KBLKMIN = IBLKOFF
SELF%KBLKMAX = SELF%KGPBLKS+IBLKOFF-1

CALL FIELD_NEW (SELF%YLFINDS, UBOUNDS=[2, SELF%KLON_G, SELF%KGPBLKS_G], PERSISTENT=.TRUE.)
INDS => GET_HOST_DATA_RDWR (SELF%YLFINDS)

! Create indices (serial code)

JBLKG = 1
JLONG = 1
DO JBLKS = 1, SELF%KGPBLKS_S
  DO JLONS = 1, MIN (SELF%KLON_S, SELF%KGPTOT_S - (JBLKS - 1) * SELF%KLON_S)
    INDS (NLONDIM, JLONG, JBLKG) = JLONS
    INDS (NBLKDIM, JLONG, JBLKG) = JBLKS + IBLKOFF-1
    JLONG = JLONG + 1
    IF (JLONG > SELF%KLON_G) THEN
      JLONG = 1
      JBLKG = JBLKG + 1
    ENDIF
  ENDDO
ENDDO

IF (JBLKG <= SIZE (INDS, 3)) THEN
  DO WHILE (JLONG <= SELF%KLON_G)
    INDS (NLONDIM, JLONG, JBLKG) = -9999999
    INDS (NBLKDIM, JLONG, JBLKG) = -9999999
    JLONG = JLONG + 1
  ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE SCATTER_FIELD_SHUFFLE (SELF)
CLASS (FIELD_SHUFFLE) :: SELF
TYPE (FIELD_2RM_SHUFFLE_PAIR), POINTER :: FIELD_2RM_LIST, FIELD_2RM_NEXT
TYPE (FIELD_3RM_SHUFFLE_PAIR), POINTER :: FIELD_3RM_LIST, FIELD_3RM_NEXT
TYPE (FIELD_4RM_SHUFFLE_PAIR), POINTER :: FIELD_4RM_LIST, FIELD_4RM_NEXT
TYPE (FIELD_5RM_SHUFFLE_PAIR), POINTER :: FIELD_5RM_LIST, FIELD_5RM_NEXT
TYPE (FIELD_2RD_SHUFFLE_PAIR), POINTER :: FIELD_2RD_LIST, FIELD_2RD_NEXT
TYPE (FIELD_3RD_SHUFFLE_PAIR), POINTER :: FIELD_3RD_LIST, FIELD_3RD_NEXT
TYPE (FIELD_4RD_SHUFFLE_PAIR), POINTER :: FIELD_4RD_LIST, FIELD_4RD_NEXT
TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER :: FIELD_5RD_LIST, FIELD_5RD_NEXT
TYPE (FIELD_2IM_SHUFFLE_PAIR), POINTER :: FIELD_2IM_LIST, FIELD_2IM_NEXT
TYPE (FIELD_3IM_SHUFFLE_PAIR), POINTER :: FIELD_3IM_LIST, FIELD_3IM_NEXT
TYPE (FIELD_4IM_SHUFFLE_PAIR), POINTER :: FIELD_4IM_LIST, FIELD_4IM_NEXT
TYPE (FIELD_5IM_SHUFFLE_PAIR), POINTER :: FIELD_5IM_LIST, FIELD_5IM_NEXT
TYPE (FIELD_2LM_SHUFFLE_PAIR), POINTER :: FIELD_2LM_LIST, FIELD_2LM_NEXT
TYPE (FIELD_3LM_SHUFFLE_PAIR), POINTER :: FIELD_3LM_LIST, FIELD_3LM_NEXT
TYPE (FIELD_4LM_SHUFFLE_PAIR), POINTER :: FIELD_4LM_LIST, FIELD_4LM_NEXT
TYPE (FIELD_5LM_SHUFFLE_PAIR), POINTER :: FIELD_5LM_LIST, FIELD_5LM_NEXT

IF (SELF%LNULL) THEN
  ! Do nothing
ELSEIF (SELF%LFULL) THEN
  ! Do nothing
ELSE

  CALL PAIR_SCATTER_DATA (SELF%FIELD_2RM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_3RM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_4RM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_5RM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_2RD_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_3RD_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_4RD_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_5RD_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_2IM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_3IM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_4IM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_5IM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_2LM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_3LM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_4LM_LIST, SELF%YLFINDS)

  CALL PAIR_SCATTER_DATA (SELF%FIELD_5LM_LIST, SELF%YLFINDS)


  CALL FIELD_DELETE (SELF%YLFINDS)

ENDIF

SELF%YLFINDS => NULL ()
SELF%KGPBLKS_G = -1 
SELF%KLON_G = -1 
SELF%KGPTOT_G = -1
SELF%KGPBLKS_S = -1 
SELF%KLON_S = -1 
SELF%KGPTOT_S = -1

SELF%KGPTOT  =  -1
SELF%KLON    =  -1
SELF%KGPBLKS =  -1


END SUBROUTINE

END MODULE FIELD_SHUFFLE_TYPE_MODULE
