
MODULE FIELD_4RD_GATHER_MODULE


USE FIELD_4RD_MODULE
USE FIELD_4RD_ACCESS_MODULE
USE FIELD_4RD_FACTORY_MODULE
USE FIELD_SHUFFLE_TYPE_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_4RD_SHUFFLE_MODULE


IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_SHUFFLE


PUBLIC :: FIELD_4RD_GATHER_DEVICE_DATA_RDONLY

PUBLIC :: SFIELD_4RD_GATHER_DEVICE_DATA_RDONLY


PUBLIC :: FIELD_4RD_GATHER_DEVICE_DATA_RDWR

PUBLIC :: SFIELD_4RD_GATHER_DEVICE_DATA_RDWR


PUBLIC :: FIELD_4RD_GATHER_HOST_DATA_RDONLY

PUBLIC :: SFIELD_4RD_GATHER_HOST_DATA_RDONLY


PUBLIC :: FIELD_4RD_GATHER_HOST_DATA_RDWR

PUBLIC :: SFIELD_4RD_GATHER_HOST_DATA_RDWR


CONTAINS

FUNCTION FIELD_4RD_GATHER_DEVICE_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4RD),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4RD_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_4RD_GATHER_DEVICE_DATA_RDONLY

SUBROUTINE SFIELD_4RD_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRD),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4RD),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDONLY (SELF%FIELD_4RD_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4RD_GATHER_DEVICE_DATA_RDONLY

FUNCTION FIELD_4RD_GATHER_DEVICE_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4RD),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4RD_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_4RD_GATHER_DEVICE_DATA_RDWR

SUBROUTINE SFIELD_4RD_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRD),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4RD),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDWR (SELF%FIELD_4RD_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4RD_GATHER_DEVICE_DATA_RDWR

FUNCTION FIELD_4RD_GATHER_HOST_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4RD),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4RD_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_4RD_GATHER_HOST_DATA_RDONLY

SUBROUTINE SFIELD_4RD_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRD),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4RD),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDONLY (SELF%FIELD_4RD_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4RD_GATHER_HOST_DATA_RDONLY

FUNCTION FIELD_4RD_GATHER_HOST_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4RD),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4RD_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_4RD_GATHER_HOST_DATA_RDWR

SUBROUTINE SFIELD_4RD_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRD),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4RD),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDWR (SELF%FIELD_4RD_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4RD_GATHER_HOST_DATA_RDWR


END MODULE FIELD_4RD_GATHER_MODULE
