
MODULE FIELD_SHUFFLE_TYPE_MODULE


USE FIELD_3IM_MODULE, ONLY : FIELD_3IM
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_2RM_SHUFFLE_MODULE
USE FIELD_3RM_SHUFFLE_MODULE
USE FIELD_4RM_SHUFFLE_MODULE
USE FIELD_5RM_SHUFFLE_MODULE
USE FIELD_2RD_SHUFFLE_MODULE
USE FIELD_3RD_SHUFFLE_MODULE
USE FIELD_4RD_SHUFFLE_MODULE
USE FIELD_5RD_SHUFFLE_MODULE
USE FIELD_2IM_SHUFFLE_MODULE
USE FIELD_3IM_SHUFFLE_MODULE
USE FIELD_4IM_SHUFFLE_MODULE
USE FIELD_5IM_SHUFFLE_MODULE
USE FIELD_2LM_SHUFFLE_MODULE
USE FIELD_3LM_SHUFFLE_MODULE
USE FIELD_4LM_SHUFFLE_MODULE
USE FIELD_5LM_SHUFFLE_MODULE

IMPLICIT NONE

PRIVATE


END MODULE FIELD_SHUFFLE_TYPE_MODULE
