
MODULE FIELD_4IM_GATHER_MODULE


USE FIELD_4IM_MODULE
USE FIELD_4IM_ACCESS_MODULE
USE FIELD_4IM_FACTORY_MODULE
USE FIELD_SHUFFLE_TYPE_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_4IM_SHUFFLE_MODULE


IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_SHUFFLE


PUBLIC :: FIELD_4IM_GATHER_DEVICE_DATA_RDONLY

PUBLIC :: SFIELD_4IM_GATHER_DEVICE_DATA_RDONLY


PUBLIC :: FIELD_4IM_GATHER_DEVICE_DATA_RDWR

PUBLIC :: SFIELD_4IM_GATHER_DEVICE_DATA_RDWR


PUBLIC :: FIELD_4IM_GATHER_HOST_DATA_RDONLY

PUBLIC :: SFIELD_4IM_GATHER_HOST_DATA_RDONLY


PUBLIC :: FIELD_4IM_GATHER_HOST_DATA_RDWR

PUBLIC :: SFIELD_4IM_GATHER_HOST_DATA_RDWR


CONTAINS

FUNCTION FIELD_4IM_GATHER_DEVICE_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4IM),   POINTER, INTENT (IN) :: YLF

INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4IM_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_4IM_GATHER_DEVICE_DATA_RDONLY

SUBROUTINE SFIELD_4IM_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
INTEGER(KIND=JPIM),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4IM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDONLY (SELF%FIELD_4IM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4IM_GATHER_DEVICE_DATA_RDONLY

FUNCTION FIELD_4IM_GATHER_DEVICE_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4IM),   POINTER, INTENT (IN) :: YLF

INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4IM_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_4IM_GATHER_DEVICE_DATA_RDWR

SUBROUTINE SFIELD_4IM_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
INTEGER(KIND=JPIM),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4IM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDWR (SELF%FIELD_4IM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4IM_GATHER_DEVICE_DATA_RDWR

FUNCTION FIELD_4IM_GATHER_HOST_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4IM),   POINTER, INTENT (IN) :: YLF

INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4IM_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_4IM_GATHER_HOST_DATA_RDONLY

SUBROUTINE SFIELD_4IM_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
INTEGER(KIND=JPIM),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4IM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDONLY (SELF%FIELD_4IM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4IM_GATHER_HOST_DATA_RDONLY

FUNCTION FIELD_4IM_GATHER_HOST_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_4IM),   POINTER, INTENT (IN) :: YLF

INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)

CALL SFIELD_4IM_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_4IM_GATHER_HOST_DATA_RDWR

SUBROUTINE SFIELD_4IM_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
INTEGER(KIND=JPIM),           POINTER             :: PTR(:,:,:,:)
CLASS (FIELD_4IM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDWR (SELF%FIELD_4IM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_4IM_GATHER_HOST_DATA_RDWR


END MODULE FIELD_4IM_GATHER_MODULE
