
MODULE FIELD_5RM_GATHER_MODULE


USE FIELD_5RM_MODULE
USE FIELD_5RM_ACCESS_MODULE
USE FIELD_5RM_FACTORY_MODULE
USE FIELD_SHUFFLE_TYPE_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_5RM_SHUFFLE_MODULE


IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_SHUFFLE


PUBLIC :: FIELD_5RM_GATHER_DEVICE_DATA_RDONLY

PUBLIC :: SFIELD_5RM_GATHER_DEVICE_DATA_RDONLY


PUBLIC :: FIELD_5RM_GATHER_DEVICE_DATA_RDWR

PUBLIC :: SFIELD_5RM_GATHER_DEVICE_DATA_RDWR


PUBLIC :: FIELD_5RM_GATHER_HOST_DATA_RDONLY

PUBLIC :: SFIELD_5RM_GATHER_HOST_DATA_RDONLY


PUBLIC :: FIELD_5RM_GATHER_HOST_DATA_RDWR

PUBLIC :: SFIELD_5RM_GATHER_HOST_DATA_RDWR


CONTAINS

FUNCTION FIELD_5RM_GATHER_DEVICE_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5RM),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5RM_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_5RM_GATHER_DEVICE_DATA_RDONLY

SUBROUTINE SFIELD_5RM_GATHER_DEVICE_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5RM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDONLY (SELF%FIELD_5RM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5RM_GATHER_DEVICE_DATA_RDONLY

FUNCTION FIELD_5RM_GATHER_DEVICE_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5RM),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5RM_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_5RM_GATHER_DEVICE_DATA_RDWR

SUBROUTINE SFIELD_5RM_GATHER_DEVICE_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5RM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_DEVICE_DATA_RDWR (SELF%FIELD_5RM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5RM_GATHER_DEVICE_DATA_RDWR

FUNCTION FIELD_5RM_GATHER_HOST_DATA_RDONLY (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5RM),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5RM_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF)

END FUNCTION FIELD_5RM_GATHER_HOST_DATA_RDONLY

SUBROUTINE SFIELD_5RM_GATHER_HOST_DATA_RDONLY (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5RM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDONLY (SELF%FIELD_5RM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5RM_GATHER_HOST_DATA_RDONLY

FUNCTION FIELD_5RM_GATHER_HOST_DATA_RDWR (SELF, YLF) RESULT (PTR)

CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_5RM),   POINTER, INTENT (IN) :: YLF

REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:,:)

CALL SFIELD_5RM_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF)

END FUNCTION FIELD_5RM_GATHER_HOST_DATA_RDWR

SUBROUTINE SFIELD_5RM_GATHER_HOST_DATA_RDWR (SELF, PTR, YLF) 

CLASS (FIELD_SHUFFLE)                      :: SELF
REAL(KIND=JPRM),           POINTER             :: PTR(:,:,:,:,:)
CLASS (FIELD_5RM),   POINTER, OPTIONAL   :: YLF


CALL PAIR_GATHER_HOST_DATA_RDWR (SELF%FIELD_5RM_LIST, SELF%LNULL, SELF%LFULL, &
& SELF%KLON_G, SELF%KGPBLKS_G, SELF%YLFINDS, PTR, YLF, SELF%KBLKMIN, SELF%KBLKMAX)

END SUBROUTINE SFIELD_5RM_GATHER_HOST_DATA_RDWR


END MODULE FIELD_5RM_GATHER_MODULE
