
MODULE DEV_ALLOC_MODULE


USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE, INTRINSIC :: ISO_C_BINDING

IMPLICIT NONE

INTERFACE DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5LM_DEV_ALLOCATE_HST
END INTERFACE

INTERFACE DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5LM_DEV_ALLOCATE_DIM
END INTERFACE

INTERFACE DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5LM_DEV_DEALLOCATE
END INTERFACE

INTERFACE
  SUBROUTINE DEV_MALLOC (SIZ, PTR) BIND (C, NAME='dev_malloc')
    IMPORT :: C_PTR, C_SIZE_T
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZ
    TYPE (C_PTR), INTENT(OUT) :: PTR
  END SUBROUTINE
  SUBROUTINE DEV_FREE (PTR) BIND (C, NAME='dev_free')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: PTR
  END SUBROUTINE
END INTERFACE


CONTAINS




SUBROUTINE FIELD_1RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRM), POINTER :: DEV(:)
REAL(KIND=JPRM), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (1)
INTEGER :: IUBOUNDS (1)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_1RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_1RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
INTEGER (KIND=JPIM) :: ILBOUNDS (1)
REAL(KIND=JPRM), POINTER :: TMP(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_1RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_1RM_DEV_DEALLOCATE




SUBROUTINE FIELD_2RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRM), POINTER :: DEV(:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (2)
INTEGER :: IUBOUNDS (2)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_2RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_2RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
INTEGER (KIND=JPIM) :: ILBOUNDS (2)
REAL(KIND=JPRM), POINTER :: TMP(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_2RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_2RM_DEV_DEALLOCATE




SUBROUTINE FIELD_3RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRM), POINTER :: DEV(:,:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (3)
INTEGER :: IUBOUNDS (3)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_3RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_3RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
REAL(KIND=JPRM), POINTER :: TMP(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_3RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_3RM_DEV_DEALLOCATE




SUBROUTINE FIELD_4RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (4)
INTEGER :: IUBOUNDS (4)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_4RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_4RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)
INTEGER (KIND=JPIM) :: ILBOUNDS (4)
REAL(KIND=JPRM), POINTER :: TMP(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_4RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_4RM_DEV_DEALLOCATE




SUBROUTINE FIELD_5RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (5)
INTEGER :: IUBOUNDS (5)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_5RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_5RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)
INTEGER (KIND=JPIM) :: ILBOUNDS (5)
REAL(KIND=JPRM), POINTER :: TMP(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(5)-ILBOUNDS(5)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):, ILBOUNDS (5):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_5RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4), LBOUND (DEV, 5)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_5RM_DEV_DEALLOCATE




SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRD), POINTER :: DEV(:)
REAL(KIND=JPRD), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (1)
INTEGER :: IUBOUNDS (1)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_1RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
INTEGER (KIND=JPIM) :: ILBOUNDS (1)
REAL(KIND=JPRD), POINTER :: TMP(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_1RD_DEV_DEALLOCATE




SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRD), POINTER :: DEV(:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (2)
INTEGER :: IUBOUNDS (2)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_2RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
INTEGER (KIND=JPIM) :: ILBOUNDS (2)
REAL(KIND=JPRD), POINTER :: TMP(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_2RD_DEV_DEALLOCATE




SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (3)
INTEGER :: IUBOUNDS (3)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_3RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
REAL(KIND=JPRD), POINTER :: TMP(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_3RD_DEV_DEALLOCATE




SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (4)
INTEGER :: IUBOUNDS (4)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_4RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)
INTEGER (KIND=JPIM) :: ILBOUNDS (4)
REAL(KIND=JPRD), POINTER :: TMP(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_4RD_DEV_DEALLOCATE




SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (5)
INTEGER :: IUBOUNDS (5)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_5RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)
INTEGER (KIND=JPIM) :: ILBOUNDS (5)
REAL(KIND=JPRD), POINTER :: TMP(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(5)-ILBOUNDS(5)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):, ILBOUNDS (5):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4), LBOUND (DEV, 5)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_5RD_DEV_DEALLOCATE




SUBROUTINE FIELD_1IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

INTEGER(KIND=JPIM), POINTER :: DEV(:)
INTEGER(KIND=JPIM), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (1)
INTEGER :: IUBOUNDS (1)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_1IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_1IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
INTEGER (KIND=JPIM) :: ILBOUNDS (1)
INTEGER(KIND=JPIM), POINTER :: TMP(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_1IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_1IM_DEV_DEALLOCATE




SUBROUTINE FIELD_2IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

INTEGER(KIND=JPIM), POINTER :: DEV(:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (2)
INTEGER :: IUBOUNDS (2)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_2IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_2IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
INTEGER (KIND=JPIM) :: ILBOUNDS (2)
INTEGER(KIND=JPIM), POINTER :: TMP(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_2IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_2IM_DEV_DEALLOCATE




SUBROUTINE FIELD_3IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (3)
INTEGER :: IUBOUNDS (3)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_3IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_3IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
INTEGER(KIND=JPIM), POINTER :: TMP(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_3IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_3IM_DEV_DEALLOCATE




SUBROUTINE FIELD_4IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (4)
INTEGER :: IUBOUNDS (4)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_4IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_4IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)
INTEGER (KIND=JPIM) :: ILBOUNDS (4)
INTEGER(KIND=JPIM), POINTER :: TMP(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_4IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_4IM_DEV_DEALLOCATE




SUBROUTINE FIELD_5IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (5)
INTEGER :: IUBOUNDS (5)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_5IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_5IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)
INTEGER (KIND=JPIM) :: ILBOUNDS (5)
INTEGER(KIND=JPIM), POINTER :: TMP(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(5)-ILBOUNDS(5)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):, ILBOUNDS (5):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_5IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4), LBOUND (DEV, 5)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_5IM_DEV_DEALLOCATE




SUBROUTINE FIELD_1LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

LOGICAL(KIND=JPLM), POINTER :: DEV(:)
LOGICAL(KIND=JPLM), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (1)
INTEGER :: IUBOUNDS (1)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_1LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_1LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
INTEGER (KIND=JPIM) :: ILBOUNDS (1)
LOGICAL(KIND=JPLM), POINTER :: TMP(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_1LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_1LM_DEV_DEALLOCATE




SUBROUTINE FIELD_2LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (2)
INTEGER :: IUBOUNDS (2)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_2LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_2LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
INTEGER (KIND=JPIM) :: ILBOUNDS (2)
LOGICAL(KIND=JPLM), POINTER :: TMP(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_2LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_2LM_DEV_DEALLOCATE




SUBROUTINE FIELD_3LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (3)
INTEGER :: IUBOUNDS (3)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_3LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_3LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
LOGICAL(KIND=JPLM), POINTER :: TMP(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_3LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_3LM_DEV_DEALLOCATE




SUBROUTINE FIELD_4LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (4)
INTEGER :: IUBOUNDS (4)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_4LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_4LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)
INTEGER (KIND=JPIM) :: ILBOUNDS (4)
LOGICAL(KIND=JPLM), POINTER :: TMP(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_4LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_4LM_DEV_DEALLOCATE




SUBROUTINE FIELD_5LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

INTEGER :: ILBOUNDS (5)
INTEGER :: IUBOUNDS (5)

ILBOUNDS = LBOUND (HST)
IUBOUNDS = UBOUND (HST)

CALL FIELD_5LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS=IUBOUNDS, LBOUNDS=ILBOUNDS, MAP_DEVPTR=MAP_DEVPTR)

END SUBROUTINE FIELD_5LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)
INTEGER (KIND=JPIM) :: ILBOUNDS (5)
LOGICAL(KIND=JPLM), POINTER :: TMP(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR

TYPE (C_PTR) :: PTR
INTEGER (C_SIZE_T) :: SIZ

ILBOUNDS = 1
IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

SIZ = KIND (DEV)
SIZ = SIZ * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(3)-ILBOUNDS(3)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(4)-ILBOUNDS(4)+1, C_SIZE_T)
SIZ = SIZ * INT (UBOUNDS(5)-ILBOUNDS(5)+1, C_SIZE_T)

IF(MAP_DEVPTR)THEN
  CALL DEV_MALLOC (SIZ, PTR)
ELSE
ENDIF

CALL C_F_POINTER (PTR, TMP, UBOUNDS-ILBOUNDS+1)
DEV (ILBOUNDS (1):, ILBOUNDS (2):, ILBOUNDS (3):, ILBOUNDS (4):, ILBOUNDS (5):) => TMP

IF(MAP_DEVPTR)THEN

ENDIF

IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_ALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

END SUBROUTINE FIELD_5LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)

USE FIELD_STATISTICS_MODULE

LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR
TYPE (C_PTR) :: PTR

IF (ASSOCIATED (DEV)) THEN

  IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_DEVICE_DEALLOCATE (SIZE (DEV, KIND=JPIB) * INT (KIND (DEV), KIND=JPIB))

  PTR = C_LOC (DEV (LBOUND (DEV, 1), LBOUND (DEV, 2), LBOUND (DEV, 3), LBOUND (DEV, 4), LBOUND (DEV, 5)))
  
  IF(MAP_DEVPTR)THEN
    CALL DEV_FREE (PTR)
    
  ELSE
  ENDIF

  NULLIFY (DEV)

ENDIF

END SUBROUTINE FIELD_5LM_DEV_DEALLOCATE



END MODULE DEV_ALLOC_MODULE
