
MODULE FIELD_1LM_DATA_MODULE


USE FIELD_CONSTANTS_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


PUBLIC :: FIELD_1LM_COPY
PUBLIC :: FIELD_1LM_COPY_FUNC
PUBLIC :: FIELD_1LM_COPY_INTF

ABSTRACT INTERFACE
  SUBROUTINE FIELD_1LM_COPY_INTF (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
    IMPORT :: JPIM, JPLM
    LOGICAL(KIND=JPLM), POINTER :: HST (:), DEV (:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
  END SUBROUTINE
END INTERFACE

CONTAINS


  FUNCTION FIELD_1LM_COPY_FUNC (HST, DEV) RESULT (FUNC)

    USE FIELD_ABORT_MODULE

    PROCEDURE (FIELD_1LM_COPY_INTF), POINTER :: FUNC 

    LOGICAL(KIND=JPLM), POINTER, OPTIONAL :: HST (:), DEV (:)

    INTEGER :: LAST_CONTIG_DIM
    INTEGER :: NEXT_CONTIG_DIM

    IF (PRESENT (HST)) THEN
      LAST_CONTIG_DIM = FIELD_1LM_GET_LAST_CONTIGUOUS_DIMENSION (HST, 0)
      NEXT_CONTIG_DIM = FIELD_1LM_GET_LAST_CONTIGUOUS_DIMENSION (HST, LAST_CONTIG_DIM+1)
    ELSE
      LAST_CONTIG_DIM = 1
      NEXT_CONTIG_DIM = 1
    ENDIF

    SELECT CASE (LAST_CONTIG_DIM)
      CASE (0)
        FUNC => FIELD_1LM_COPY_DIM0_CONTIGUOUS 
      CASE (1)
        FUNC => FIELD_1LM_COPY_DIM1_CONTIGUOUS 
      CASE DEFAULT
        CALL FIELD_ABORT ('INTERNAL ERROR: UNEXPECTED LAST_CONTIG_DIM')
    END SELECT

  END FUNCTION

  SUBROUTINE FIELD_1LM_COPY (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)

    USE FIELD_ABORT_MODULE

    LOGICAL(KIND=JPLM), POINTER :: HST (:), DEV (:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE

    PROCEDURE (FIELD_1LM_COPY_INTF), POINTER :: FUNC 

    FUNC => FIELD_1LM_COPY_FUNC (HST, DEV) 

    CALL FUNC (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)

  END SUBROUTINE

  SUBROUTINE FIELD_1LM_COPY_DIM0_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
  
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    LOGICAL(KIND=JPLM), POINTER :: HST (:), DEV (:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J1
    

    DO J1 = LBOUND (HST, 1), UBOUND (HST, 1)
#ifdef WITH_GPU_OFFLOAD
      IF(MAP_DEVPTR)THEN

        DEVPTR = 

      ELSE

        DEVPTR = 

      ENDIF
#endif
      ISIZE = KIND (HST)
      IF (KDIR == NH2D) THEN
#ifdef WITH_GPU_OFFLOAD
        IF(PRESENT(QUEUE))THEN
          
        ELSE
          
        ENDIF
#else
        DEV (J1 + LBOUND(DEV,1) - LBOUND (HST,1)) = HST (J1)
#endif
      ELSEIF (KDIR == ND2H) THEN
#ifdef WITH_GPU_OFFLOAD
        IF(PRESENT(QUEUE))THEN
          
        ELSE
          
        ENDIF
#else
        HST (J1) = DEV (J1 + LBOUND(DEV,1) - LBOUND (HST,1))
#endif
      ENDIF
    ENDDO
    END SUBROUTINE

  SUBROUTINE FIELD_1LM_COPY_DIM1_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
  
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    LOGICAL(KIND=JPLM), POINTER :: HST (:), DEV (:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J
    

#ifdef WITH_GPU_OFFLOAD
        IF(MAP_DEVPTR)THEN
 
          DEVPTR = 
 
        ELSE
 
          DEVPTR = 
 
        ENDIF
#endif
        ISIZE = SIZEOF ( HST(:) )
        IF (KDIR == NH2D) THEN
#ifdef WITH_GPU_OFFLOAD
          IF(PRESENT(QUEUE))THEN
           
          ELSE
           
          ENDIF
#else
          DEV (:) = HST (:)
#endif
        ELSEIF (KDIR == ND2H) THEN
#ifdef WITH_GPU_OFFLOAD
          IF(PRESENT(QUEUE))THEN
           
          ELSE
           
          ENDIF
#else
          HST (:) = DEV (:)
#endif
        ENDIF
    END SUBROUTINE





  INTEGER (KIND=JPIM) FUNCTION FIELD_1LM_GET_LAST_CONTIGUOUS_DIMENSION (PTR, AFTER) RESULT (JDIM)
  LOGICAL(KIND=JPLM), POINTER :: PTR (:)
  INTEGER (KIND=JPIM) :: AFTER
  INTEGER*8 :: IPREVIOUS_STRIDE, ITHIS_STRIDE, ISIZE
  INTEGER (KIND=JPIM) :: J, LB(1)

  ! assume that dimension all dimensions before AFTER are contiguous...
  LB = LBOUND(PTR)
  IF (AFTER == 0) THEN
    IPREVIOUS_STRIDE = KIND (PTR)
  ENDIF

  IF (AFTER < 1) THEN
    ISIZE = 1
    IF (SIZE(PTR, 1) /= 1) THEN
      ITHIS_STRIDE = LOC (PTR (LB(1)+1)) - LOC (PTR (LB(1)))
      IF (IPREVIOUS_STRIDE * ISIZE /= ITHIS_STRIDE) THEN
        JDIM = 0
        RETURN
      ENDIF
    ENDIF
    IPREVIOUS_STRIDE = IPREVIOUS_STRIDE * ISIZE
  ELSE IF (AFTER == 1) THEN
    ITHIS_STRIDE = LOC (PTR (LB(1)+1)) - LOC (PTR (LB(1)))
    IPREVIOUS_STRIDE = ITHIS_STRIDE
  ENDIF

  JDIM = 1
  END FUNCTION FIELD_1LM_GET_LAST_CONTIGUOUS_DIMENSION


END MODULE FIELD_1LM_DATA_MODULE
