
MODULE HOST_ALLOC_MODULE


USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM
USE, INTRINSIC::ISO_C_BINDING
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
USE FIELD_DEFAULTS_MODULE
USE FIELD_STATISTICS_MODULE
USE FIELD_ABORT_MODULE

IMPLICIT NONE

PRIVATE

INTERFACE HOST_ALLOC
  MODULE PROCEDURE FIELD_1RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_2RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_3RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_4RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_5RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_1RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_2RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_3RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_4RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_5RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_1IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_2IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_3IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_4IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_5IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_1LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_2LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_3LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_4LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_5LM_HOST_ALLOC
END INTERFACE HOST_ALLOC

INTERFACE HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_1RM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_2RM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_3RM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_4RM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_5RM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_1RD_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_2RD_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_3RD_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_4RD_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_5RD_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_1IM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_2IM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_3IM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_4IM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_5IM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_1LM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_2LM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_3LM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_4LM_HOST_ALLOC_POOLED
  MODULE PROCEDURE FIELD_5LM_HOST_ALLOC_POOLED
END INTERFACE HOST_ALLOC_POOLED

INTERFACE HOST_DEALLOC
  MODULE PROCEDURE FIELD_1RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_1RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_1IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_1LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5LM_HOST_DEALLOC
END INTERFACE HOST_DEALLOC

INTERFACE HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_1RM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_2RM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_3RM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_4RM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_5RM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_1RD_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_2RD_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_3RD_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_4RD_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_5RD_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_1IM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_2IM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_3IM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_4IM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_5IM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_1LM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_2LM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_3LM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_4LM_HOST_DEALLOC_POOLED
  MODULE PROCEDURE FIELD_5LM_HOST_DEALLOC_POOLED
END INTERFACE HOST_DEALLOC_POOLED

INTERFACE
  SUBROUTINE C_MALLOC (SIZ, PTR) BIND (C, NAME='c_malloc')
    IMPORT :: C_PTR, C_SIZE_T
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZ
    TYPE (C_PTR), INTENT(OUT) :: PTR
  END SUBROUTINE C_MALLOC
  SUBROUTINE C_FREE (PTR) BIND (C, NAME='c_free')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: PTR
  END SUBROUTINE C_FREE
  SUBROUTINE C_PTR_INCR (SIZ, PTR, DATA) BIND (C, NAME='c_ptr_incr')
    IMPORT :: C_PTR, C_SIZE_T
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZ
    TYPE (C_PTR), INTENT(IN) :: PTR
    TYPE (C_PTR), INTENT(OUT) :: DATA
  END SUBROUTINE C_PTR_INCR
END INTERFACE


TYPE :: MEM_BLOCK
  TYPE(C_PTR) :: DATA = C_NULL_PTR
  INTEGER(KIND=INT64) :: POS = 0
  INTEGER(KIND=INT64) :: SIZE = 0
  INTEGER :: NUMFLDS = 0

  TYPE(MEM_BLOCK), POINTER :: NEXT => NULL()

  CONTAINS

  PROCEDURE :: INIT => MEM_BLOCK_INIT
  PROCEDURE :: FINAL => MEM_BLOCK_FINAL
  PROCEDURE :: ALLOC => MEM_BLOCK_ALLOC
  PROCEDURE :: DEALLOC => MEM_BLOCK_DEALLOC

END TYPE MEM_BLOCK

TYPE :: MEM_POOL
  TYPE(MEM_BLOCK), POINTER :: START_BLK => NULL()
  
  CONTAINS

  PROCEDURE :: ALLOC => MEM_POOL_ALLOC
  PROCEDURE :: DEALLOC => MEM_POOL_DEALLOC
  PROCEDURE :: REQUEST_MEM => MEM_POOL_REQUEST_MEM
  PROCEDURE :: REQUEST_FREE => MEM_POOL_REQUEST_FREE
  PROCEDURE :: FINAL => MEM_POOL_FINAL
  PROCEDURE, PRIVATE :: MEM_FREE => MEM_POOL_MEM_FREE

END TYPE MEM_POOL

TYPE(MEM_POOL) :: HOST_POOL

PUBLIC :: HOST_ALLOC
PUBLIC :: HOST_ALLOC_POOLED
PUBLIC :: HOST_DEALLOC
PUBLIC :: HOST_DEALLOC_POOLED
PUBLIC :: HOST_POOL

CONTAINS

SUBROUTINE MEM_BLOCK_INIT( SELF )
   CLASS(MEM_BLOCK) :: SELF

   CALL C_MALLOC(SELF%SIZE, SELF%DATA)


END SUBROUTINE MEM_BLOCK_INIT

SUBROUTINE MEM_BLOCK_ALLOC( SELF, ALLOC_SIZE, DATA )
   CLASS(MEM_BLOCK) :: SELF
   INTEGER(C_SIZE_T), INTENT(IN) :: ALLOC_SIZE
   TYPE(C_PTR), INTENT(OUT) :: DATA

   CALL C_PTR_INCR(SELF%POS, SELF%DATA, DATA)
   SELF%POS = SELF%POS + ALLOC_SIZE

   SELF%NUMFLDS = SELF%NUMFLDS + 1

END SUBROUTINE MEM_BLOCK_ALLOC

SUBROUTINE MEM_BLOCK_DEALLOC( SELF )
   CLASS(MEM_BLOCK) :: SELF

   SELF%NUMFLDS = SELF%NUMFLDS - 1
   IF( SELF%NUMFLDS == 0 ) SELF%POS = 0

END SUBROUTINE MEM_BLOCK_DEALLOC

SUBROUTINE MEM_BLOCK_FINAL( SELF )
   CLASS(MEM_BLOCK) :: SELF

   IF( .NOT. SELF%NUMFLDS == 0 )THEN
      PRINT *, "FIELD_API DETECTED UNFINALISED FIELDS, POTENTIAL DEVICE MEMORY LEAK"
   ENDIF


   CALL C_FREE(SELF%DATA)
   SELF%SIZE = 0
   SELF%POS = 0
   SELF%NUMFLDS = 0
END SUBROUTINE MEM_BLOCK_FINAL

SUBROUTINE MEM_POOL_FINAL( SELF )
   CLASS(MEM_POOL) :: SELF

   IF( ASSOCIATED(SELF%START_BLK) ) CALL SELF%MEM_FREE(SELF%START_BLK)
END SUBROUTINE MEM_POOL_FINAL

SUBROUTINE MEM_POOL_MEM_FREE(SELF, BLK)
   CLASS(MEM_POOL) :: SELF
   TYPE(MEM_BLOCK), POINTER, INTENT(INOUT) :: BLK

   IF( ASSOCIATED(BLK%NEXT) ) CALL SELF%MEM_FREE(BLK%NEXT)
   CALL BLK%FINAL()
   DEALLOCATE(BLK)
   NULLIFY(BLK)
END SUBROUTINE MEM_POOL_MEM_FREE

SUBROUTINE MEM_POOL_ALLOC( SELF, ARR_SIZE, BLKID, DATA )
   CLASS(MEM_POOL) :: SELF
   INTEGER(C_SIZE_T), INTENT(IN) :: ARR_SIZE
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID
   TYPE(C_PTR), INTENT(OUT) :: DATA
   INTEGER(C_SIZE_T) :: ALLOC_SIZE

   ALLOC_SIZE = ARR_SIZE + MOD(ARR_SIZE, POOL_ALLOC_PADDING_FACTOR)

   IF( .NOT. ASSOCIATED(SELF%START_BLK) ) ALLOCATE(SELF%START_BLK)
   CALL SELF%REQUEST_MEM( ALLOC_SIZE, SELF%START_BLK, DATA, BLKID )

END SUBROUTINE MEM_POOL_ALLOC

SUBROUTINE MEM_POOL_DEALLOC( SELF, FIELD_BLKID )
   CLASS(MEM_POOL) :: SELF
   INTEGER(KIND=JPIM), INTENT(IN) :: FIELD_BLKID
   INTEGER(KIND=JPIM) :: BLKID

   BLKID = 1
   CALL SELF%REQUEST_FREE( FIELD_BLKID, SELF%START_BLK, BLKID )
END SUBROUTINE MEM_POOL_DEALLOC

SUBROUTINE MEM_POOL_REQUEST_FREE( SELF, FIELD_BLKID, BLK, BLKID )
   CLASS(MEM_POOL) :: SELF
   INTEGER(KIND=JPIM), INTENT(IN) :: FIELD_BLKID
   TYPE(MEM_BLOCK), POINTER, INTENT(INOUT) :: BLK
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   IF( FIELD_BLKID == BLKID )THEN
      CALL BLK%DEALLOC()
   ELSE
      BLKID = BLKID + 1
      CALL SELF%REQUEST_FREE(FIELD_BLKID, BLK%NEXT, BLKID)
   ENDIF

END SUBROUTINE MEM_POOL_REQUEST_FREE

SUBROUTINE MEM_POOL_REQUEST_MEM( SELF, ALLOC_SIZE, BLK, DATA, BLKID )
   CLASS(MEM_POOL) :: SELF
   INTEGER(C_SIZE_T), INTENT(IN) :: ALLOC_SIZE
   TYPE(MEM_BLOCK), POINTER, INTENT(INOUT) :: BLK
   TYPE(C_PTR), INTENT(OUT) :: DATA
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   BLKID = BLKID + 1

   IF( C_ASSOCIATED(BLK%DATA) )THEN
      IF( BLK%POS + ALLOC_SIZE <= BLK%SIZE ) THEN
         !... Allocation can fit within existing block
         CALL BLK%ALLOC(ALLOC_SIZE, DATA)
      ELSE
         !... Proceed to next block
         IF( .NOT. ASSOCIATED(BLK%NEXT) ) ALLOCATE(BLK%NEXT)
         CALL SELF%REQUEST_MEM(ALLOC_SIZE, BLK%NEXT, DATA, BLKID)
      ENDIF
   ELSE
     !... Create new block
     BLK%SIZE = POOL_BLOCK_SIZE
     DO WHILE ( BLK%SIZE < ALLOC_SIZE )
        BLK%SIZE = BLK%SIZE*2
     ENDDO
     CALL BLK%INIT()
     CALL BLK%ALLOC(ALLOC_SIZE, DATA)
   ENDIF

END SUBROUTINE MEM_POOL_REQUEST_MEM


SUBROUTINE FIELD_1RM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRM), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1RM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_1RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRM), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1RM_HOST_ALLOC

SUBROUTINE FIELD_1RM_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1RM_HOST_DEALLOC

SUBROUTINE FIELD_1RM_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)
   INTEGER :: UBOUNDS(1)
   INTEGER :: LBOUNDS(1)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1RM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_2RM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRM), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2RM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_2RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRM), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2RM_HOST_ALLOC

SUBROUTINE FIELD_2RM_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2RM_HOST_DEALLOC

SUBROUTINE FIELD_2RM_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)
   INTEGER :: UBOUNDS(2)
   INTEGER :: LBOUNDS(2)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2RM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_3RM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRM), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3RM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_3RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRM), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3RM_HOST_ALLOC

SUBROUTINE FIELD_3RM_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3RM_HOST_DEALLOC

SUBROUTINE FIELD_3RM_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)
   INTEGER :: UBOUNDS(3)
   INTEGER :: LBOUNDS(3)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3RM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_4RM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4RM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_4RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4RM_HOST_ALLOC

SUBROUTINE FIELD_4RM_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4RM_HOST_DEALLOC

SUBROUTINE FIELD_4RM_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)
   INTEGER :: UBOUNDS(4)
   INTEGER :: LBOUNDS(4)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4RM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_5RM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5RM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_5RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRM), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5RM_HOST_ALLOC

SUBROUTINE FIELD_5RM_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4), LBOUND (HST, 5)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5RM_HOST_DEALLOC

SUBROUTINE FIELD_5RM_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)
   INTEGER :: UBOUNDS(5)
   INTEGER :: LBOUNDS(5)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5RM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_1RD_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRD), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1RD_HOST_ALLOC_POOLED

SUBROUTINE FIELD_1RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRD), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1RD_HOST_ALLOC

SUBROUTINE FIELD_1RD_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1RD_HOST_DEALLOC

SUBROUTINE FIELD_1RD_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)
   INTEGER :: UBOUNDS(1)
   INTEGER :: LBOUNDS(1)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1RD_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_2RD_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRD), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2RD_HOST_ALLOC_POOLED

SUBROUTINE FIELD_2RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRD), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2RD_HOST_ALLOC

SUBROUTINE FIELD_2RD_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2RD_HOST_DEALLOC

SUBROUTINE FIELD_2RD_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)
   INTEGER :: UBOUNDS(2)
   INTEGER :: LBOUNDS(2)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2RD_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_3RD_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRD), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3RD_HOST_ALLOC_POOLED

SUBROUTINE FIELD_3RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRD), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3RD_HOST_ALLOC

SUBROUTINE FIELD_3RD_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3RD_HOST_DEALLOC

SUBROUTINE FIELD_3RD_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)
   INTEGER :: UBOUNDS(3)
   INTEGER :: LBOUNDS(3)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3RD_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_4RD_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4RD_HOST_ALLOC_POOLED

SUBROUTINE FIELD_4RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4RD_HOST_ALLOC

SUBROUTINE FIELD_4RD_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4RD_HOST_DEALLOC

SUBROUTINE FIELD_4RD_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)
   INTEGER :: UBOUNDS(4)
   INTEGER :: LBOUNDS(4)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4RD_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_5RD_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5RD_HOST_ALLOC_POOLED

SUBROUTINE FIELD_5RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   LOGICAL, INTENT(IN) :: PINNED

   REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5RD_HOST_ALLOC

SUBROUTINE FIELD_5RD_HOST_DEALLOC(HST, PINNED)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4), LBOUND (HST, 5)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5RD_HOST_DEALLOC

SUBROUTINE FIELD_5RD_HOST_DEALLOC_POOLED(HST, BLKID)

   REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)
   INTEGER :: UBOUNDS(5)
   INTEGER :: LBOUNDS(5)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5RD_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_1IM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   INTEGER(KIND=JPIM), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1IM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_1IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   LOGICAL, INTENT(IN) :: PINNED

   INTEGER(KIND=JPIM), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1IM_HOST_ALLOC

SUBROUTINE FIELD_1IM_HOST_DEALLOC(HST, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1IM_HOST_DEALLOC

SUBROUTINE FIELD_1IM_HOST_DEALLOC_POOLED(HST, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)
   INTEGER :: UBOUNDS(1)
   INTEGER :: LBOUNDS(1)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1IM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_2IM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2IM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_2IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   LOGICAL, INTENT(IN) :: PINNED

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2IM_HOST_ALLOC

SUBROUTINE FIELD_2IM_HOST_DEALLOC(HST, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2IM_HOST_DEALLOC

SUBROUTINE FIELD_2IM_HOST_DEALLOC_POOLED(HST, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)
   INTEGER :: UBOUNDS(2)
   INTEGER :: LBOUNDS(2)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2IM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_3IM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3IM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_3IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   LOGICAL, INTENT(IN) :: PINNED

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3IM_HOST_ALLOC

SUBROUTINE FIELD_3IM_HOST_DEALLOC(HST, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3IM_HOST_DEALLOC

SUBROUTINE FIELD_3IM_HOST_DEALLOC_POOLED(HST, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)
   INTEGER :: UBOUNDS(3)
   INTEGER :: LBOUNDS(3)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3IM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_4IM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4IM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_4IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   LOGICAL, INTENT(IN) :: PINNED

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4IM_HOST_ALLOC

SUBROUTINE FIELD_4IM_HOST_DEALLOC(HST, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4IM_HOST_DEALLOC

SUBROUTINE FIELD_4IM_HOST_DEALLOC_POOLED(HST, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)
   INTEGER :: UBOUNDS(4)
   INTEGER :: LBOUNDS(4)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4IM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_5IM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5IM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_5IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   LOGICAL, INTENT(IN) :: PINNED

   INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5IM_HOST_ALLOC

SUBROUTINE FIELD_5IM_HOST_DEALLOC(HST, PINNED)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4), LBOUND (HST, 5)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5IM_HOST_DEALLOC

SUBROUTINE FIELD_5IM_HOST_DEALLOC_POOLED(HST, BLKID)

   INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)
   INTEGER :: UBOUNDS(5)
   INTEGER :: LBOUNDS(5)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5IM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_1LM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   LOGICAL(KIND=JPLM), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1LM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_1LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
   LOGICAL, INTENT(IN) :: PINNED

   LOGICAL(KIND=JPLM), POINTER :: PTR(:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_1LM_HOST_ALLOC

SUBROUTINE FIELD_1LM_HOST_DEALLOC(HST, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1LM_HOST_DEALLOC

SUBROUTINE FIELD_1LM_HOST_DEALLOC_POOLED(HST, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(1)
   INTEGER :: UBOUNDS(1)
   INTEGER :: LBOUNDS(1)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_1LM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_2LM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2LM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_2LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
   LOGICAL, INTENT(IN) :: PINNED

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_2LM_HOST_ALLOC

SUBROUTINE FIELD_2LM_HOST_DEALLOC(HST, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2LM_HOST_DEALLOC

SUBROUTINE FIELD_2LM_HOST_DEALLOC_POOLED(HST, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(2)
   INTEGER :: UBOUNDS(2)
   INTEGER :: LBOUNDS(2)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_2LM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_3LM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3LM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_3LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
   LOGICAL, INTENT(IN) :: PINNED

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_3LM_HOST_ALLOC

SUBROUTINE FIELD_3LM_HOST_DEALLOC(HST, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3LM_HOST_DEALLOC

SUBROUTINE FIELD_3LM_HOST_DEALLOC_POOLED(HST, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(3)
   INTEGER :: UBOUNDS(3)
   INTEGER :: LBOUNDS(3)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_3LM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_4LM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4LM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_4LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
   LOGICAL, INTENT(IN) :: PINNED

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_4LM_HOST_ALLOC

SUBROUTINE FIELD_4LM_HOST_DEALLOC(HST, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4LM_HOST_DEALLOC

SUBROUTINE FIELD_4LM_HOST_DEALLOC_POOLED(HST, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(4)
   INTEGER :: UBOUNDS(4)
   INTEGER :: LBOUNDS(4)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_4LM_HOST_DEALLOC_POOLED

SUBROUTINE FIELD_5LM_HOST_ALLOC_POOLED (HST, LBOUNDS, UBOUNDS, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(INOUT) :: BLKID

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5), ISTAT

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%ALLOC(ARR_SIZE, BLKID, DATA)
     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)

     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5LM_HOST_ALLOC_POOLED

SUBROUTINE FIELD_5LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
   INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
   LOGICAL, INTENT(IN) :: PINNED

   LOGICAL(KIND=JPLM), POINTER :: PTR(:,:,:,:,:)
   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)

   IF(ARR_SIZE > 0)THEN
     CALL C_MALLOC(ARR_SIZE, DATA)


     CALL C_F_POINTER(DATA, PTR, SHAPE=ISHAPE)
     HST(LBOUNDS(1):, LBOUNDS(2):, LBOUNDS(3):, LBOUNDS(4):, LBOUNDS(5):) => PTR
   ELSE
     ALLOCATE(HST(LBOUNDS(1):UBOUNDS(1),LBOUNDS(2):UBOUNDS(2),LBOUNDS(3):UBOUNDS(3),LBOUNDS(4):UBOUNDS(4),LBOUNDS(5):UBOUNDS(5)))
   ENDIF

   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_ALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

END SUBROUTINE FIELD_5LM_HOST_ALLOC

SUBROUTINE FIELD_5LM_HOST_DEALLOC(HST, PINNED)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   LOGICAL, INTENT (IN) :: PINNED

   TYPE(C_PTR) :: DATA
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(SIZE(HST) > 0)THEN
     DATA = C_LOC (HST (LBOUND (HST, 1), LBOUND (HST, 2), LBOUND (HST, 3), LBOUND (HST, 4), LBOUND (HST, 5)))


     CALL C_FREE(DATA)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5LM_HOST_DEALLOC

SUBROUTINE FIELD_5LM_HOST_DEALLOC_POOLED(HST, BLKID)

   LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
   INTEGER(KIND=JPIM), INTENT(IN) :: BLKID

   TYPE(C_PTR) :: DATA
   INTEGER(C_SIZE_T) :: ARR_SIZE
   INTEGER :: ISHAPE(5)
   INTEGER :: UBOUNDS(5)
   INTEGER :: LBOUNDS(5)

  UBOUNDS = UBOUND(HST)
  LBOUNDS = LBOUND(HST)

   ARR_SIZE = KIND(HST)
   ISHAPE(1) = UBOUNDS(1) - LBOUNDS(1) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(1)
   ISHAPE(2) = UBOUNDS(2) - LBOUNDS(2) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(2)
   ISHAPE(3) = UBOUNDS(3) - LBOUNDS(3) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(3)
   ISHAPE(4) = UBOUNDS(4) - LBOUNDS(4) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(4)
   ISHAPE(5) = UBOUNDS(5) - LBOUNDS(5) + 1
   ARR_SIZE = ARR_SIZE * ISHAPE(5)
  
   IF (FIELD_STATISTICS_ENABLE) CALL FIELD_STATISTICS_HOST_DEALLOCATE (SIZE (HST, KIND=JPIB) * INT (KIND (HST), KIND=JPIB))

   IF(ARR_SIZE > 0)THEN
     CALL HOST_POOL%DEALLOC(BLKID)
   ELSE
     DEALLOCATE(HST)
   ENDIF

   NULLIFY(HST)

END SUBROUTINE FIELD_5LM_HOST_DEALLOC_POOLED


END MODULE HOST_ALLOC_MODULE
