SUBROUTINE INIT_SNOW_LW

IMPLICIT NONE

TYPE SURF_SNOW

CHARACTER(LEN=3)                :: SCHEME    
REAL, DIMENSION(:,:), POINTER :: WSNOW       
REAL, DIMENSION(:,:), POINTER :: HEAT        
REAL, DIMENSION(:,:), POINTER :: RHO         
REAL, DIMENSION(:)  , POINTER :: TS          
END TYPE SURF_SNOW

INTERFACE SNOW3LSCAP
  PROCEDURE SNOW3LSCAP_1D
END INTERFACE


REAL          :: PEMISSN 
TYPE(SURF_SNOW)  :: TPSNOW  

IF (TPSNOW%SCHEME=='3-L' .OR. TPSNOW%SCHEME=='CRO') THEN
  WHERE(TPSNOW%WSNOW(:,1)==0. .OR. TPSNOW%WSNOW(:,1)==1.0 )
    TPSNOW%TS (:)= 1.0
  ELSEWHERE
    TPSNOW%TS(:) = 2. + (TPSNOW%HEAT(:,1) + 3. * TPSNOW%RHO(:,1)) / SNOW3LSCAP(TPSNOW%RHO(:,1))  
    TPSNOW%TS(:) = MIN(2., TPSNOW%TS(:))
  END WHERE
END IF

CONTAINS

FUNCTION SNOW3LSCAP_1D(PSNOWRHO) RESULT(PSCAP)

IMPLICIT NONE

REAL, DIMENSION(:), INTENT(IN)                   :: PSNOWRHO
REAL, DIMENSION(SIZE(PSNOWRHO))                  :: PSCAP

PSCAP(:) = PSNOWRHO(:)*1.0      

END FUNCTION SNOW3LSCAP_1D

END SUBROUTINE INIT_SNOW_LW
