
MODULE FIELD_1LM_ACCESS_MODULE


USE FIELD_1LM_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE SGET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDONLY_FIELD_1LM
END INTERFACE SGET_DEVICE_DATA_RDONLY

PUBLIC :: SGET_DEVICE_DATA_RDONLY

INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_1LM
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE SGET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: SGET_HOST_DATA_RDONLY_FIELD_1LM
END INTERFACE SGET_HOST_DATA_RDONLY

PUBLIC :: SGET_HOST_DATA_RDONLY

INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_1LM
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE SGET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDWR_FIELD_1LM
END INTERFACE SGET_DEVICE_DATA_RDWR

PUBLIC :: SGET_DEVICE_DATA_RDWR

INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_1LM
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE SGET_HOST_DATA_RDWR
  MODULE PROCEDURE :: SGET_HOST_DATA_RDWR_FIELD_1LM
END INTERFACE SGET_HOST_DATA_RDWR

PUBLIC :: SGET_HOST_DATA_RDWR

INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_1LM
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


LOGICAL(KIND=JPLM), TARGET, SAVE :: DUMMY_FIELD_1LM (1)



CONTAINS


  SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_1LM (PTR, FIELD_PTR) 
    USE FIELD_DEFAULTS_MODULE

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)
    INTEGER*8 :: ICRC
    CHARACTER*1024 :: CLBT
    CHARACTER*10 :: CLF
    INTEGER :: ILEN, IP1, IP2


    ICRC = 0

    IF (PRESENT (FIELD_PTR)) THEN
      IF (ASSOCIATED (FIELD_PTR)) THEN
        CALL FIELD_PTR%GET_DEVICE_DATA_RDONLY (PTR)

        IF (GET_DEBUG_PRINT_CRC) THEN
          ICRC = FIELD_PTR%CRC64 ()
        ENDIF

      ELSE
        PTR => DUMMY_FIELD_1LM
      ENDIF
    ELSE
      PTR => DUMMY_FIELD_1LM
    ENDIF


    IF (GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, '(Z16.16," ")', ADVANCE='NO') ICRC
    ENDIF
    
    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      CLF = "FIELD_1LM"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "RDONLY"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "DEVICE"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION) THEN
      ILEN = LEN (CLBT)
      IP1 = 2
      IP2 = 2 + GET_DEBUG_PRINT_LOCATION_DEPTH
      CALL FIELD_BACKTRACE (CLBT, IP1, IP2, ILEN)
      WRITE (0, '(A)', ADVANCE='NO') CLBT (1:ILEN)
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, *)
    ENDIF

  END SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_1LM

  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

    CALL SGET_DEVICE_DATA_RDONLY_FIELD_1LM (PTR, FIELD_PTR)

  END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_1LM



  SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_1LM (PTR, FIELD_PTR) 
    USE FIELD_DEFAULTS_MODULE

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)
    INTEGER*8 :: ICRC
    CHARACTER*1024 :: CLBT
    CHARACTER*10 :: CLF
    INTEGER :: ILEN, IP1, IP2


    ICRC = 0

    IF (PRESENT (FIELD_PTR)) THEN
      IF (ASSOCIATED (FIELD_PTR)) THEN
        CALL FIELD_PTR%GET_HOST_DATA_RDONLY (PTR)

        IF (GET_DEBUG_PRINT_CRC) THEN
          ICRC = FIELD_PTR%CRC64 ()
        ENDIF

      ELSE
        PTR => DUMMY_FIELD_1LM
      ENDIF
    ELSE
      PTR => DUMMY_FIELD_1LM
    ENDIF


    IF (GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, '(Z16.16," ")', ADVANCE='NO') ICRC
    ENDIF
    
    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      CLF = "FIELD_1LM"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "RDONLY"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "HOST"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION) THEN
      ILEN = LEN (CLBT)
      IP1 = 2
      IP2 = 2 + GET_DEBUG_PRINT_LOCATION_DEPTH
      CALL FIELD_BACKTRACE (CLBT, IP1, IP2, ILEN)
      WRITE (0, '(A)', ADVANCE='NO') CLBT (1:ILEN)
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, *)
    ENDIF

  END SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_1LM

  FUNCTION GET_HOST_DATA_RDONLY_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

    CALL SGET_HOST_DATA_RDONLY_FIELD_1LM (PTR, FIELD_PTR)

  END FUNCTION GET_HOST_DATA_RDONLY_FIELD_1LM



  SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_1LM (PTR, FIELD_PTR) 
    USE FIELD_DEFAULTS_MODULE

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)
    INTEGER*8 :: ICRC
    CHARACTER*1024 :: CLBT
    CHARACTER*10 :: CLF
    INTEGER :: ILEN, IP1, IP2


    ICRC = 0

    IF (PRESENT (FIELD_PTR)) THEN
      IF (ASSOCIATED (FIELD_PTR)) THEN
        CALL FIELD_PTR%GET_DEVICE_DATA_RDWR (PTR)

        IF (GET_DEBUG_PRINT_CRC) THEN
          ICRC = FIELD_PTR%CRC64 ()
        ENDIF

      ELSE
        PTR => DUMMY_FIELD_1LM
      ENDIF
    ELSE
      PTR => DUMMY_FIELD_1LM
    ENDIF


    IF (GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, '(Z16.16," ")', ADVANCE='NO') ICRC
    ENDIF
    
    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      CLF = "FIELD_1LM"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "RDWR"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "DEVICE"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION) THEN
      ILEN = LEN (CLBT)
      IP1 = 2
      IP2 = 2 + GET_DEBUG_PRINT_LOCATION_DEPTH
      CALL FIELD_BACKTRACE (CLBT, IP1, IP2, ILEN)
      WRITE (0, '(A)', ADVANCE='NO') CLBT (1:ILEN)
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, *)
    ENDIF

  END SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_1LM

  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

    CALL SGET_DEVICE_DATA_RDWR_FIELD_1LM (PTR, FIELD_PTR)

  END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_1LM



  SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_1LM (PTR, FIELD_PTR) 
    USE FIELD_DEFAULTS_MODULE

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)
    INTEGER*8 :: ICRC
    CHARACTER*1024 :: CLBT
    CHARACTER*10 :: CLF
    INTEGER :: ILEN, IP1, IP2


    ICRC = 0

    IF (PRESENT (FIELD_PTR)) THEN
      IF (ASSOCIATED (FIELD_PTR)) THEN
        CALL FIELD_PTR%GET_HOST_DATA_RDWR (PTR)

        IF (GET_DEBUG_PRINT_CRC) THEN
          ICRC = FIELD_PTR%CRC64 ()
        ENDIF

      ELSE
        PTR => DUMMY_FIELD_1LM
      ENDIF
    ELSE
      PTR => DUMMY_FIELD_1LM
    ENDIF


    IF (GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, '(Z16.16," ")', ADVANCE='NO') ICRC
    ENDIF
    
    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      CLF = "FIELD_1LM"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "RDWR"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
      CLF = "HOST"
      WRITE (0, '(A10)', ADVANCE='NO') CLF
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION) THEN
      ILEN = LEN (CLBT)
      IP1 = 2
      IP2 = 2 + GET_DEBUG_PRINT_LOCATION_DEPTH
      CALL FIELD_BACKTRACE (CLBT, IP1, IP2, ILEN)
      WRITE (0, '(A)', ADVANCE='NO') CLBT (1:ILEN)
    ENDIF

    IF (GET_DEBUG_PRINT_LOCATION .OR. GET_DEBUG_PRINT_CRC) THEN
      WRITE (0, *)
    ENDIF

  END SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_1LM

  FUNCTION GET_HOST_DATA_RDWR_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

    CALL SGET_HOST_DATA_RDWR_FIELD_1LM (PTR, FIELD_PTR)

  END FUNCTION GET_HOST_DATA_RDWR_FIELD_1LM



END MODULE FIELD_1LM_ACCESS_MODULE
