MODULE FIELD_5RM_ARRAY_UTIL_MODULE


USE FIELD_5RM_ARRAY_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_5RM_ARRAY
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_5RM_ARRAY
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_5RM_ARRAY
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_5RM_ARRAY
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_5RM_ARRAY
END INTERFACE


CONTAINS


SUBROUTINE LOAD_FIELD_5RM_ARRAY (KLUN, YD)

USE FIELD_5RM_UTIL_MODULE, ONLY : LOAD

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_5RM_ARRAY) :: YD

IF (ASSOCIATED (YD%F_P)) THEN
  CALL LOAD (KLUN, YD%F_P)
ENDIF

END SUBROUTINE

SUBROUTINE SAVE_FIELD_5RM_ARRAY (KLUN, YD)

USE FIELD_5RM_UTIL_MODULE, ONLY : SAVE

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_5RM_ARRAY) :: YD
END SUBROUTINE

SUBROUTINE COPY_FIELD_5RM_ARRAY (SELF, LDCREATED, LDFIELDAPI)

USE FIELD_5RM_UTIL_MODULE, ONLY : COPY

TYPE (FIELD_5RM_ARRAY) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED, LDFIELDAPI
LOGICAL :: LLFIELDAPI, LLCREATED

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) LLFIELDAPI = LDFIELDAPI

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) LLCREATED = LDCREATED

IF (.NOT. LLCREATED) THEN
  
  
ENDIF


NULLIFY (SELF%P)
NULLIFY (SELF%F_P)


IF (LLFIELDAPI .AND. ASSOCIATED (SELF%F_P)) THEN
  CALL COPY (SELF%F_P, LDCREATED)
ENDIF

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_5RM_ARRAY (SELF, LDDELETED, LDFIELDAPI)

USE FIELD_5RM_UTIL_MODULE, ONLY : WIPE

TYPE (FIELD_5RM_ARRAY) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED, LDFIELDAPI
LOGICAL :: LLFIELDAPI, LLDELETED

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) LLFIELDAPI = LDFIELDAPI

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) LLDELETED = LDDELETED

IF (LLFIELDAPI .AND. ASSOCIATED (SELF%F_P)) THEN
  CALL WIPE (SELF%F_P, LDDELETED)
ENDIF

IF (.NOT. LLDELETED) THEN
  
ENDIF

END SUBROUTINE 

SUBROUTINE HOST_FIELD_5RM_ARRAY (SELF)

USE FIELD_5RM_UTIL_MODULE, ONLY : HOST

TYPE (FIELD_5RM_ARRAY) :: SELF

IF (ASSOCIATED (SELF%F_P)) THEN
  CALL HOST (SELF%F_P)
ENDIF

END SUBROUTINE 


END MODULE
