
MODULE FIELD_4RM_UTIL_MODULE


USE FIELD_4RM_MODULE
USE FIELD_4RM_ACCESS_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE


INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_4RM
  MODULE PROCEDURE LOAD_FIELD_4RM_PTR
  MODULE PROCEDURE LOAD_FIELD_4RM_VIEW
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_4RM
  MODULE PROCEDURE SAVE_FIELD_4RM_PTR
  MODULE PROCEDURE SAVE_FIELD_4RM_VIEW
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_4RM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_4RM
  MODULE PROCEDURE COPY_FIELD_4RM_PTR
  MODULE PROCEDURE COPY_FIELD_4RM_VIEW
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_4RM
  MODULE PROCEDURE WIPE_FIELD_4RM_PTR
  MODULE PROCEDURE WIPE_FIELD_4RM_VIEW
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_4RM
  MODULE PROCEDURE HOST_FIELD_4RM_PTR
  MODULE PROCEDURE HOST_FIELD_4RM_VIEW
END INTERFACE

INTERFACE LEGACY
  MODULE PROCEDURE LEGACY_FIELD_4RM
END INTERFACE

INTERFACE CRC64
  MODULE PROCEDURE CRC64_FIELD_4RM
END INTERFACE


CONTAINS

INTEGER*8 FUNCTION CRC64_FIELD_4RM (YD)
CLASS (FIELD_4RM), POINTER :: YD
INTEGER*8 :: ICRC

ICRC = 0

IF (ASSOCIATED (YD)) THEN
  ICRC = YD%CRC64 ()
ENDIF

CRC64_FIELD_4RM = ICRC

END FUNCTION

SUBROUTINE LOAD_FIELD_4RM (KLUN, YD)

USE FIELD_ABORT_MODULE
USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_4RM), POINTER :: YD

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE

SUBROUTINE SAVE_FIELD_4RM (KLUN, YD)

USE FIELD_ABORT_MODULE
USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_4RM), POINTER :: YD

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE

SUBROUTINE DIFF_FIELD_4RM (CDMESS, YD, YO)

USE FIELD_ABORT_MODULE

CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_4RM), POINTER :: YD, YO

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE

SUBROUTINE COPY_FIELD_4RM (SELF, LDCREATED)

USE FIELD_ABORT_MODULE

CLASS (FIELD_4RM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE 

SUBROUTINE WIPE_FIELD_4RM (SELF, LDDELETED)

USE FIELD_ABORT_MODULE

CLASS (FIELD_4RM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE 

SUBROUTINE HOST_FIELD_4RM (SELF)
CLASS (FIELD_4RM), POINTER :: SELF

CALL SELF%SYNC_HOST_RDWR ()

END SUBROUTINE 

SUBROUTINE LEGACY_FIELD_4RM (SELF, KADDRL, KADDRU, KDIR)

USE FIELD_4RM_ACCESS_MODULE
USE FIELD_CONSTANTS_MODULE

CLASS (FIELD_4RM), POINTER :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER,   INTENT (IN) :: KDIR

REAL(KIND=JPRM), POINTER :: PTR (:,:,:,:), DEVPTR (:,:,:,:)
INTEGER*8 :: IADDRL
INTEGER*8 :: IADDRU
INTEGER (KIND=JPIM) :: ILBOUNDS (4)
INTEGER (KIND=JPIM) :: IUBOUNDS (4)

IF (ASSOCIATED (SELF)) THEN

  CALL SELF%GET_DIMS (LBOUNDS=ILBOUNDS, UBOUNDS=IUBOUNDS)

  PTR => SELF%PTR

  IADDRL = LOC (PTR (ILBOUNDS(1),ILBOUNDS(2),ILBOUNDS(3),ILBOUNDS(4)))
  IADDRU = LOC (PTR (IUBOUNDS(1),IUBOUNDS(2),IUBOUNDS(3),IUBOUNDS(4)))

  IF ((KADDRL <= IADDRL) .AND. (IADDRU <= KADDRU)) THEN

    IF (KDIR == NF2L) THEN
      DEVPTR => GET_DEVICE_DATA_RDONLY (SELF)
      CALL LEGACY_FIELD_4RM_ASSIGN (PTR, DEVPTR)
    ELSEIF (KDIR == NL2F) THEN
      DEVPTR => GET_DEVICE_DATA_RDWR (SELF)
      CALL LEGACY_FIELD_4RM_ASSIGN (DEVPTR, PTR)
    ENDIF

  ENDIF

ENDIF

CONTAINS

SUBROUTINE LEGACY_FIELD_4RM_ASSIGN (PTR_RHS, PTR_LHS)

REAL(KIND=JPRM) :: PTR_RHS (:,:,:,:), PTR_LHS (:,:,:,:)


PTR_RHS = PTR_LHS


END SUBROUTINE

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_4RM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_4RM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE SAVE_FIELD_4RM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_4RM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE COPY_FIELD_4RM_VIEW (SELF, LDCREATED)
CLASS (FIELD_4RM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
! Do nothing
END SUBROUTINE 

SUBROUTINE WIPE_FIELD_4RM_VIEW (SELF, LDDELETED)
CLASS (FIELD_4RM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
! Do nothing
END SUBROUTINE 

SUBROUTINE HOST_FIELD_4RM_VIEW (SELF)
CLASS (FIELD_4RM_VIEW) :: SELF
! Do nothing
END SUBROUTINE 


SUBROUTINE LOAD_FIELD_4RM_PTR (KLUN, YD)

USE FIELD_ABORT_MODULE
USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_4RM_PTR) :: YD

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE

SUBROUTINE SAVE_FIELD_4RM_PTR (KLUN, YD)

USE FIELD_ABORT_MODULE
USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_4RM_PTR) :: YD

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE

SUBROUTINE COPY_FIELD_4RM_PTR (SELF, LDCREATED)

USE FIELD_ABORT_MODULE

CLASS (FIELD_4RM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE 

SUBROUTINE WIPE_FIELD_4RM_PTR (SELF, LDDELETED)

USE FIELD_ABORT_MODULE

CLASS (FIELD_4RM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

CALL FIELD_ABORT ('NOT IMPLEMENTED')
END SUBROUTINE 

SUBROUTINE HOST_FIELD_4RM_PTR (SELF)
CLASS (FIELD_4RM_PTR) :: SELF

IF (ASSOCIATED (SELF%PTR)) THEN
  CALL HOST (SELF%PTR)
ENDIF

END SUBROUTINE 


END MODULE
