MODULE CPG_XXX_TYPE_MOD

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4, JPIB = 8


ABSTRACT INTERFACE 
  LOGICAL FUNCTION FUN_GREP ()
  END FUNCTION
END INTERFACE

PRIVATE :: FUN_GREP



PRIVATE :: GREPVARSF

TYPE CPG_XXXF_2RB
  REAL (KIND=JPRB) :: PARITY = 1._JPRB
  INTEGER (KIND=JPIM) :: JFLD1 = -1, JFLD2 = -1
END TYPE

TYPE CPG_XXXF_TYPE
  LOGICAL :: LOWNED = .FALSE.
  INTEGER (KIND=JPIM) :: NLEV = -1
  INTEGER (KIND=JPIB) :: ISIZE = 0

CONTAINS
  PROCEDURE :: INIT => CPG_XXXF_TYPE_INIT

END TYPE CPG_XXXF_TYPE

CONTAINS

SUBROUTINE GREPVARSF (YDCPG_XXXF, COND)
TYPE(CPG_XXXF_TYPE), INTENT(INOUT) :: YDCPG_XXXF
PROCEDURE (FUN_GREP) :: COND

INTEGER (KIND=JPIM) :: ISIZE, JFLD, IPNTR


WRITE (0, *) __FILE__, ':', __LINE__; CALL FLUSH (0)

ISIZE = 0

IF (COND ()) ISIZE = ISIZE + 1

WRITE (0, *) __FILE__, ':', __LINE__; CALL FLUSH (0)

IF (COND ()) ISIZE = ISIZE + 1

STOP


WRITE (0, *) __FILE__, ':', __LINE__; CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE CPG_XXXF_TYPE_INIT (SELF)

CLASS (CPG_XXXF_TYPE),TARGET                 :: SELF

INTEGER :: NLEV

NLEV = 15

CALL GREPVARSF (SELF, COND_GFL)

CONTAINS

SUBROUTINE ADD3FSL (YD3FSL, K3FSL, CDNAME, CDKIND, KFLD)

TYPE (CPG_XXXF_2RB) :: YD3FSL (:)
INTEGER (KIND=JPIM) :: K3FSL
CHARACTER (LEN=*),    INTENT (IN) :: CDNAME
CHARACTER (LEN=*),    INTENT (IN) :: CDKIND
INTEGER (KIND=JPIM),  INTENT (IN) :: KFLD

K3FSL = K3FSL + 1

YD3FSL (K3FSL)%PARITY = 1. 
YD3FSL (K3FSL)%JFLD1  = KFLD
YD3FSL (K3FSL)%JFLD2  = KFLD+NLEV+1

END SUBROUTINE


LOGICAL FUNCTION COND_GFL ()
  COND_GFL = .TRUE.
END FUNCTION


END SUBROUTINE CPG_XXXF_TYPE_INIT

END MODULE CPG_XXX_TYPE_MOD

