MODULE UTIL_NSV_T_MOD
  TYPE NSV_t
    CHARACTER(LEN=16), DIMENSION(:,:), ALLOCATABLE :: CSV_CHEM_LIST_A
    CHARACTER(LEN=16),             DIMENSION(:,:), ALLOCATABLE :: CSV_A
    CHARACTER(LEN=16), DIMENSION(:), POINTER :: CSV_CHEM_LIST
  END TYPE NSV_t

CONTAINS
  SUBROUTINE COPY_NSV_T(YD)
    IMPLICIT NONE
    TYPE(NSV_T), INTENT(IN), TARGET :: YD
    !$OMP TARGET ENTER DATA MAP (ALLOC:YD%CSV_CHEM_LIST_A)
    !$OMP TARGET UPDATE TO (YD%CSV_CHEM_LIST_A)
    !$OMP TARGET ENTER DATA MAP (TO:YD%CSV_CHEM_LIST_A)
    !$OMP TARGET ENTER DATA MAP (ALLOC:YD%CSV_A)
    !$OMP TARGET UPDATE TO (YD%CSV_A)
    !$OMP TARGET ENTER DATA MAP (TO:YD%CSV_A)
    !$OMP TARGET ENTER DATA MAP (ALLOC:YD%CSV_CHEM_LIST)
  END SUBROUTINE

  SUBROUTINE WIPE_NSV_T(YD)
    IMPLICIT NONE
    TYPE(NSV_T), INTENT(IN), TARGET :: YD
    !$OMP TARGET EXIT DATA MAP (DELETE:YD%CSV_CHEM_LIST_A)
    !$OMP TARGET EXIT DATA MAP (DELETE:YD%CSV_A)
  END SUBROUTINE
END MODULE
